//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microservice.Whatevers.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microservice.Whatevers.Domain.DomainResource", typeof(DomainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Identificador informado para Thing é inválido..
        /// </summary>
        internal static string Thing_Identifier_invalid {
            get {
                return ResourceManager.GetString("Thing_Identifier_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome informado para Thing é inválido..
        /// </summary>
        internal static string Thing_Name_invalid {
            get {
                return ResourceManager.GetString("Thing_Name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Tipo informado para Thing é inválido..
        /// </summary>
        internal static string Thing_Type_invalid {
            get {
                return ResourceManager.GetString("Thing_Type_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Valor informado para Thing deve ser maior que zero..
        /// </summary>
        internal static string Thing_Value_less_than_zero {
            get {
                return ResourceManager.GetString("Thing_Value_less_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Identificador informado para Whatever é inválido..
        /// </summary>
        internal static string Whatever_Identifier_invalid {
            get {
                return ResourceManager.GetString("Whatever_Identifier_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome informado para Whatever é inválido..
        /// </summary>
        internal static string Whatever_Name_invalid {
            get {
                return ResourceManager.GetString("Whatever_Name_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing informado para Whatever é inválido..
        /// </summary>
        internal static string Whatever_Thing_invalid {
            get {
                return ResourceManager.GetString("Whatever_Thing_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Tempo informado para Whatever é inválido..
        /// </summary>
        internal static string Whatever_Time_invalid {
            get {
                return ResourceManager.GetString("Whatever_Time_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Tipo informado para Whatever é inválido..
        /// </summary>
        internal static string Whatever_Type_invalid {
            get {
                return ResourceManager.GetString("Whatever_Type_invalid", resourceCulture);
            }
        }
    }
}
